theme: jekyll-theme-cayman
title: "Year 9: Unit 0 - The Skill Building"
description: "An introduction unit for Wellington Y9 ICT and CS students to prepare them to be a better learner by equiping them with the right skills<br> research, presentation, time management, and information synthesis"
